export const FETCH_QUIZES_START = 'FETCH_QUIZES_START';
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR';

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE';
export const QUIZ_FINISH = 'QUIZ_FINISH';
export const QUIZ_ACTIVE_QUESTION = 'QUIZ_ACTIVE_QUESTION';
export const RESTART_QUIZ = 'RESTART_QUIZ';

export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION';
export const CREATE_QUIZ = 'CREATE_QUIZ';